### PR TITLE
Command Line Updates

### PR DESCRIPTION
**Pull request by AmyShackles**
## Adds:
- `readline` package
- Note about changing directories before installing dependencies (same as previous now closed PR, I just forgot to base this branch off of master instead of that branch, so this is a two-for).

- Commands for quitting the repl and logging to console the message "Have a nice day!":
    - .end
    - .q
    - .quit
    - quit
    - .exit
    - exit

- Commands for pulling up the help menu:
    - help
    - .help

- The ability to run the program by passing the expression to arith (not starting the repl).
    Example usage:
    > `arith '(print "Hello, world") ; -> "Hello, world"'`

    It should be noted that certain characters need to be escaped or the entire expression needs to be wrapped with single quotes (assuming that there is no expression that would contain single quotes).

    The escaped version would be:
    > `arith "(print \"Hello, world\") ; -> \"Hello, world\""`

    It should also be noted that all expressions must be wrapped by some quotation mechanism or the shell program will throw an annoying error about unknown file attributes.  Fun times.

### Removes:
- `inquirer` package

### Changes:
- If/else if/else statement in `bin/arith` to a switch statement

#### Notes:
- Created a bug where `arith version` and `arith run <file>` commands were broken, resolved by remembering to add `break` statements in switch statement.  Added a process.exit(0) for good measure, just in case.

### CODE REVIEW

**Comment by jasonsbarr** [comment]
This is actually a perfect use case for a draft pull request. 😁 

No sense closing this and opening a new one though. We can talk through it before merging.

**Comment by jasonsbarr** [comment]
Oh neat, I can convert it. I didn't know that!

**Comment by jasonsbarr** [comment]
What do you think about possibly using Node's built in `repl` module instead? We _might_ be able to just use the `evaluate` function that's already there as a custom evaluator. Or did you try that already?

**Comment by jasonsbarr** [comment]
> It should be noted that certain characters need to be escaped or the entire expression needs to be wrapped with single quotes (assuming that there is no expression that would contain single quotes)

There currently is no expression type that uses single quotes; however, there _will_ be once I get quote/quasiquote/unquote and the macro facility working.

**Comment by AmyShackles** [comment]
> What do you think about possibly using Node's built in `repl` module instead? We _might_ be able to just use the `evaluate` function that's already there as a custom evaluator. Or did you try that already?

I didn't try that, but readline's also a Node's built-in module.  If I'm being honest, I actually don't know what the pros and cons are between the two.

**Comment by jasonsbarr** [comment]
>  If I'm being honest, I actually don't know what the pros and cons are between the two

The REPL module allows you to define custom commands through its built-in API and gives you a REPL based on Node's regular REPL. You can load modules on initialization. I wonder if it would let us have multi-line editing for free, though I don't want to get my hopes up TOO much.

A search for tutorials and other articles on using the REPL module hasn't turned up much, though there is this:
https://derickbailey.com/2014/07/02/build-your-own-app-specific-repl-for-your-nodejs-app/

Documentation: https://nodejs.org/api/repl.html

This one talks about adding a function to your REPL's context environment: https://blog.bloomca.me/2018/07/09/nodejs-repl-in-depth.html

Here's a decent couple of posts from Medium that includes building a custom REPL with Express:
https://medium.com/trabe/mastering-the-node-js-repl-part-2-365c52a5203d
https://medium.com/trabe/mastering-the-node-js-repl-part-3-c0374be0d1bf

And this chapter from a book: https://www.oreilly.com/library/view/learning-node-2nd/9781491943113/ch04.html#custom_repl

**Comment by jasonsbarr** [comment]
I also think I would like to get rid of the requirement to preface files executed by the interpreter with "run."

I think it should execute a script with just `arith <file>`.

**Comment by jasonsbarr** [comment]
Does the other one mean this one can be closed?

**Comment by AmyShackles** [comment]
It does indeed!

**Comment by jasonsbarr** [comment]
Ha, beat me to it! 🤣

**Pull request closed without merging**
