### PR TITLE
Converting to repl

### PR DESCRIPTION
**Pull request by AmyShackles**
All right, so:

In a Node REPL, commands are prefaced with a ".", so your commands in-repl are going to be slightly different than the ones out of repl.  I couldn't figure out a way to load a file in-repl without making use of the ".load" command or how to allow multi-line without use of the "editor" command, but they work if you use them.

I created a "help.js" folder that contains an array of all of the help commands and descriptions available in-repl.  The hope is that that should make it easier for you to update as you move forward.  Since the commands are slightly different for the out-of-repl versions, I left those as they were for the most part, other than to update the one that runs a file.

#### In-repl commands: 
- .load
- .editor
- .exit
- .version
- .help

#### Out-of-repl commands:
- `arith <filename>` will now run a file

### CODE REVIEW

**Comment by jasonsbarr** [comment]
I like what I see so far, though I haven't yet tested it. I was under the impression though that the `help` property on the object passed to `defineCommand` defined the help message for that command in a way that hooks into the base Node REPL's `.help` command. Is that not accurate?

**Comment by jasonsbarr** [comment]
Ok, this is a definite improvement over what I had before xD

Can you make it so it doesn't print `undefined`? I think there was something about that in one of the resources I posted yesterday.

**Comment by jasonsbarr** [comment]
Also, since I don't have modules working yet, loading a file is great but kinda useless. That's not your fault AT ALL!!!, but it might be more helpful to mention `.editor` in the startup message instead of `.load`.

**Comment by AmyShackles** [comment]
> I like what I see so far, though I haven't yet tested it. I was under the impression though that the `help` property on the object passed to `defineCommand` defined the help message for that command in a way that hooks into the base Node REPL's `.help` command. Is that not accurate?

The default behavior is for .help to give you Node Repl’s help information, but you can overwrite it so that it displays your program’s help instead - figured that would be more useful to the user of your program.  Obviously can change it if you disagree.  

> Can you make it so it doesn't print undefined? I think there was something about that in one of the resources I posted yesterday.

I can try!  I’d guess it’s because it’s still console logging?   Because when you console log, it usually prints the result to console and then evaluates to undefined — that’s what it does in Repl.it, anyway.
> Also, since I don't have modules working yet, loading a file is great but kinda useless. That's not your fault AT ALL!!!, but it might be more helpful to mention `.editor` in the startup message instead of `.load`.

Noted!

> Probably shouldn't have "Use the command 'arc ' to transpile its contents to JavaScript." in the REPL help.

Noted!

> I like that up arrow lets you scroll through history. Not super thrilled that expressions from a loaded file show up in the history too, but Node does that for JavaScript files so it's not terribly surprising.
> 
> It _is_ neat that loading files work, and I think I may have actually figured out from that how to make modules work in the interpreter. In the compiler is easy because I can just piggyback off NodeJS's `require` and `exports`, but I was tying myself in knots trying to figure out how to do it in the interpreter.
> 
> Did you branch this off the branch from your other pull request? Because I don't see anything in this PR about replacing Inquirer, which means if I just merge this PR the package and require statement for it will still be there. Not that I couldn't just remove them, but this PR is your baby ;)

Haha, I actually remembered to branch from master for this one.  But I can clean up dependencies while I’m changing the help commands (removing the ones that shouldn’t be in the repl version and adding the .editor option on load).

**Comment by jasonsbarr** [comment]
Ah, I didn't realize you had to overwrite the whole `.help` command. Obviously it's useful to display help for commands that actually work. 😆 

Do you want to just bring in the other CLI changes to this PR, or remove the REPL stuff from the other and do them as 2 separate PRs? Either is fine with me.

**Comment by jasonsbarr** [comment]
Oh oh oh you should also put in the help that `.save <path/to/file>` will let you save a REPL session as a file.

Which is AWESOME.

**Comment by AmyShackles** [comment]
> Oh oh oh you should also put in the help that `.save <path/to/file>` will let you save a REPL session as a file.
> 
> Which is AWESOME.

That IS awesome.  I’ll add it to the help file.  :)

> And the info on how to keep it from logging `undefined` is in this book chapter:
> 
> https://www.oreilly.com/library/view/learning-node-2nd/9781491943113/ch04.html#custom_repl

Thanks!

> Do you want to just bring in the other CLI changes to this PR, or remove the REPL stuff from the other and do them as 2 separate PRs? Either is fine with me.

Think I’ll just bring the other changes to this PR.  :)

**Comment by jasonsbarr** [comment]
Sounds good. I'll close the other then.

**Comment by jasonsbarr** [comment]
I like what you have fine, and I don't need you to add this, but if you check the Node docs it gives info on how to do multi-line expressions without invoking `.editor` as well as how to use a custom output formatter:

https://nodejs.org/api/repl.html#repl_custom_evaluation_functions

I will later fix it so my custom pretty-print function formats the output, but there are some things I need to fix with it first before I do that (some of which I'm already working on).

**Comment by AmyShackles** [comment]
> I like what you have fine, and I don't need you to add this, but if you check the Node docs it gives info on how to do multi-line expressions without invoking `.editor` as well as how to use a custom output formatter:
> 
> https://nodejs.org/api/repl.html#repl_custom_evaluation_functions

I, uh, actually tried to implement that, and all it succeeded in doing was allowing you to hit enter and not have it immediately run and crash.  Instead, it just ran every line as undefined.  So.... no crashing, but it wasn't like it actually made it so it evaluated multiple lines.  I could have misunderstood how to use it, since the example also doesn't include how to do that when you're using a custom evaluator.

**Comment by jasonsbarr** [comment]
Looks good - very nearly there.

I like using the paren count to determine if it's a recoverable error. I use a similar trick in the parser.

You have a different number of equals signs checking for right versus left paren, and I'm about 99% sure you'd be better off using the built-in help function especially now with the whole recoverable error thing because there are 2 commands the Node help has that you don't for breaking out of the multi-line command without breaking the REPL.

It will use the help property of your command object to add that command to the help list. I looked it up.

**Comment by AmyShackles** [comment]
Updated on mobile, so here’s hoping I didn’t mess it up!

**Comment by jasonsbarr** [comment]
The evaluator works fine when it's returning numbers. It doesn't work with strings or lists. If you try the function `(list 1 2 3)` you get a syntax error on the evaluation.

I don't have any idea how to fix that off the top of my head. It's also erroring on strings.

**Comment by jasonsbarr** [comment]
Looks like you got it working! :)

**Pull request merged**
